#Alpine (OS) with node npm
FROM node:22-alpine AS build

#Has app dir
WORKDIR /app

#Copy package lock
COPY package.json package-lock.json ./
#Install
RUN npm ci

#Copy frontend code
COPY . .

#Build frontend code
RUN npm run build


#
FROM caddy:2-alpine

COPY Caddyfile /etc/caddy/Caddyfile

#Coppy /app/dist to /srv (serving)
COPY --from=build /app/dist /srv

